### ISSUE TITLE
Appcrash Error

### ISSUE THREAD

**Issue by Achef** [PrivacyVandaag/PrivacyVandaag#2]
Drear PrivacyVandaag,
How do I fix appcrash?

05-23 04:14:07.527 10104-10104/nl.privacybarometer.privacyvandaag E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: nl.privacybarometer.privacyvandaag, PID: 10104
                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{nl.privacybarometer.privacyvandaag/nl.privacybarometer.privacyvandaag.activity.HomeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int nl.privacybarometer.privacyvandaag.adapter.DrawerAdapter.getMenuPositionFromFeedId(int)' on a null object reference
                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
                                                                                        at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                                     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int nl.privacybarometer.privacyvandaag.adapter.DrawerAdapter.getMenuPositionFromFeedId(int)' on a null object reference
                                                                                        at nl.privacybarometer.privacyvandaag.activity.HomeActivity.getDrawerPositionOnIntent(HomeActivity.java:455)
                                                                                        at nl.privacybarometer.privacyvandaag.activity.HomeActivity.onCreate(HomeActivity.java:299)
                                                                                        at android.app.Activity.performCreate(Activity.java:6942)
                                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988) 
                                                                                        at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631) 
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6682) 
                                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by PrivacyVandaag** [comment]
Thanks for your message. We noticed wwe published too soon to github. This is indeed a major error in the app. We have fixed this and will published the improved version later today.

**Comment by PrivacyVandaag** [comment]
New version is available. As far as I can see it does what it should do. ;-)

**Comment by Achef** [comment]
Thank you very much for solving that issue. 

there are one more problem, 
if you reload the feeds the old one will not moving to the bottom. 
I hope you solve this issue ...

**Comment by PrivacyVandaag** [comment]
The option to reload the articles is there only for the rare situation a RSS feeds is configured wrongly. If illegal characters are present in a RSS feed, it can block the whole stream and prevent the retrieval of new articles. In that case, the user can 'reset' the feed. All the items are removed from database, includingb possible illegal (blocking) characters, and the most recent articles are again retrieved. 

This reset option has been necessary only once in the past two year, so you can also decide to remove this option from the app, since the error of a blocking feed is practically non existence.

For normal refreshing of the feed and checking whether new articles are present, just swipe down (pull down) on the screen of the feed you want to check and that specific feed is refreshed. The already existing articles are during that operation not removed but kept for as long as the user likes. The user can change the keep time of articles in the preferences / setting.

Hope this helps!
