### ISSUE TITLE
java.lang.NullPointerException: 

### ISSUE THREAD

**Issue by Achef** [PrivacyVandaag/PrivacyVandaag#3]
How can i fix it ?

java.lang.NullPointerException: 
  at nl.privacybarometer.privacyvandaag.fragment.EditFeedsListFragment$3.onStartDrag(EditFeedsListFragment.java:135)
  at nl.privacybarometer.privacyvandaag.view.DragNDropExpandableListView.startDrag(DragNDropExpandableListView.java:105)
  at nl.privacybarometer.privacyvandaag.view.DragNDropExpandableListView.onTouchEvent(DragNDropExpandableListView.java:61)
  at android.view.View.dispatchTouchEvent(View.java:10013)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2833)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2504)
  at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:5748)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2461)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2461)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2461)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2461)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2461)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2461)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2461)
  at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2869)
  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1861)
  at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
  at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
  at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
  at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2830)
  at android.view.View.dispatchPointerEvent(View.java:10248)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5488)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5324)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4763)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4816)
  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4782)
  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4923)
  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4790)
  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4980)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4763)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4816)
  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4782)
  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4790)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4763)
  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7473)
  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7341)
  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7302)
  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7583)
  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
  at android.os.MessageQueue.nativePollOnce(Native Method:0)
  at android.os.MessageQueue.next(MessageQueue.java:323)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:7331)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by PrivacyVandaag** [comment]
If I read it correctly, there is a resource missing. The nullpointer exception originates in the   onStartDrag method in EditsFeedsListFragment.java. 

The method is very simple and consists of one line only:
       @Override
            public void onStartDrag(View itemView) {
                fromHasGroupIndicator = itemView.findViewById(R.id.indicator).getVisibility() == View.VISIBLE;
            }

As far as I can see, the nullpointer is only possible if R.id.indicator == null. Are you sure you did not remove the imagefile of the indicator from the resources?

**Comment by Achef** [comment]
Yes, I remove unwanted images from resources..
how i know which image ?

**Comment by PrivacyVandaag** [comment]
I think it probably is this file: res/drawable-xhdpi/sort.png.

To safely remove resources or other elements from your project, you can use the option 'safe delete' in Android Studio. Click with right mouse button on the file in the project window. Look for 'Refactor' and go there with the pointer. A second menu inflates. Choose 'safe delete'. There yout will find also ''rename' as the recommended method for safely renaming your files , methods or classes.

**Comment by Achef** [comment]
How Can I Contact you on private?

**Comment by PrivacyVandaag** [comment]
Hi, If you have any suggestion or question about the code, it is okee for me if you post them here.

**Comment by Achef** [comment]
I Want Your Email Address, "Needs for Freelance hire".

**Comment by PrivacyVandaag** [comment]
Thanks, I didn't understand. You can contact me at 'app (at) privacybarometer.nl' . If you let me know what you are looking for, I will get back to you and let you know if and how I can help you. Cheers!
